server:
  address: 127.0.0.1
  port: 0

jena-ripper:
  settings:
    path: ${JENA_SETTINGS_PATH:}

logging:
  file:
    name: ${LOCALAPPDATA:${user.home}/AppData/Local}/JenaRipper/logs/jena-ripper.log
