rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#
rdfs=http://www.w3.org/2000/01/rdf-schema#
xsd=http://www.w3.org/2001/XMLSchema#
ups=https://cim.so-ups.ru#
cims=http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#
me=http://monitel.com/2014/schema-cim16#
dm=http://iec.ch/TC57/61970-552/DifferenceModel/1#
rf=http://gost.ru/2019/schema-cim01#
so=http://so-ups.ru/2015/schema-cim16#
md=http://iec.ch/TC57/61970-552/ModelDescription/1#
owl=http://www.w3.org/2002/07/owl#
cim=http://iec.ch/TC57/CIM100#
ti=https://www.ti-ees.ru/2025/schema-cim17#
blankNode=_:

